### ISSUE TITLE
Unclear error when the valgrind executable is not found

### ISSUE THREAD

**Issue by thedrow** [jfrimmel/cargo-valgrind#25]
I have some tests which require `sudo` to run.
When running with `sudo` you lose the path of your current user (which is expected).
I installed valgrind using linuxbrew so it shouldn't be on the standard path.
Instead of a clear error message indicating that `valgrind cannot be found` or similar all we get is `error: No such file or directory (os error 2)`.
This requires the user to guess what went wrong.

**Comment by jfrimmel** [comment]
I'll have a look, thank you for the report.

**Comment by jfrimmel** [comment]
Seems like a rather quick fix. Is the following output similar to what you expected?
```bash
     Running `target/debug/cargo-valgrind valgrind`
    Finished dev [unoptimized + debuginfo] target(s) in 0.03s
   Analyzing `target/debug/cargo-valgrind`
error: valgrind executable not found
```
