### ISSUE TITLE
Support passing arguments to the binary

### ISSUE THREAD

**Issue by lu-zero** [jfrimmel/cargo-valgrind#27]
`cargo valgrind -- --args` does not work as it does for `cargo run`.

**Comment by jfrimmel** [comment]
Duplicate of #19. I've already started working on this topic, but discontinued, since I didn't need it for myself. Since you request this feature, I hope to be able to support this soon.

**Comment by jfrimmel** [comment]
@lu-zero Please try, if it works for you now. If not, feel free to reopen this issue.

**Comment by lu-zero** [comment]
It does work well, thank you a lot!
