### ISSUE TITLE
Allow passing flags to valgrind

### ISSUE THREAD

**Issue by jfrimmel** [jfrimmel/cargo-valgrind#37]
The tool version [`1.2.0`](https://github.com/jfrimmel/cargo-valgrind/releases/tag/1.2.0), `cargo valgrind` supported _some_ valgrind flags. This ability was removed in version `2.0.0`, but should be re-introduced in version `2.1.0` (or any other future version).

I imagine passing the arguments via an environment variable like `VALGRINDFLAGS` (similar to `RUSTFLAGS` for `cargo`), as normal CLI flags are not possible (they would be passed to `cargo` instead of `valgrind`.

**Comment by jfrimmel** [comment]
A better idea would be to use a "config file chain" __and__ the environment variable, similar to what `cargo` or `git` does:
look up the config in the users home directory, search in the current directory and all parent directories for config files and look for environment variables. All of that are merged in that order, so that "closer" files override "farther away" ones. Env vars have the highest priority.

**Comment by Superhepper** [comment]
I would be really nice that would become a thing.
