### ISSUE TITLE
Calling valgrind's profiling tools?

### ISSUE THREAD

**Issue by cmpute** [jfrimmel/cargo-valgrind#56]
I wonder do you have any plans to support valgrind's callgrind and cachegrind?

I know that there's a [`cargo-profiler`](https://github.com/svenstaro/cargo-profiler) crate doing this, but the output from their tool doesn't contains enough information for me, I might write a better parser for callgrind and cachegrind output, but I'm more interested in contributing the parser to your tool.

Thanks!

**Comment by jfrimmel** [comment]
Hello and thanks for you interest in this project!

A different tool could be supported, yes. There are two main issues:
1. the user has to be able to select the tools via an additional command line flag/env var. This could be done via #58.
2. I'm not sure about this, but the XML tool output would likely be different, hence another parser is needed.

Both points are not that difficult, but do simply need work. At the moment I don't have much spare time, so I cannot add those changes in the near future. Feel free to propose a PR if you have the time 👍🏻

**Comment by jfrimmel** [comment]
Could you try out the release 2.1.0? This nicht contain the fix for your issue.

**Comment by cmpute** [comment]
Thanks for your work! I tried using `--tool=callgrind` flag but unfortunately it seems that callgrind doesn't support XML output:
```
error: invalid valgrind usage: valgrind: Bad option: --xml=yes
valgrind: Callgrind does not support XML output.
valgrind: Use --help for more information or consult the user manual.
```

**Comment by jfrimmel** [comment]
Unfortunately, I think, that this is not actionable at the moment. `cargo valgrind` builds upon the assumption to be able to parse the XML output of valgrind. If a tool does not support XML output, then this tool cannot handle it. I have to admit, that I only use the default memchecker, so other tools are rather unknown to me.

I'll go ahead and close this issue, but feel free to comment suggestions on how to deal with this issue or to re-open this issue if there is something actionable.
