### ISSUE TITLE
Passing environment variables

### ISSUE THREAD

**Issue by jkcoxson** [jfrimmel/cargo-valgrind#70]
Hello, thank your for your project.

I am encountering an issue where my program relies on the crate [env_logger](https://crates.io/crates/env_logger). It will respect my session's ``RUST_LOG`` variable and what logs to show, but this program seems to be ignoring the variable.

When spawning a new process, could cargo-valgrind move the environment variables over to the child so that I can control the logger?

**Comment by jfrimmel** [comment]
Hello, sorry for the huge delay. I wasn't able to work in this repository for some time (yes, over 2 years...).

Unfortunately I cannot reproduce; can you give some examples? Below you'll find my test:

I have the following `main.rs`, which simply prints all environment variables (the file is located at `tests/corpus/issue-70.rs`):
```rust
fn main() {
    for (key, value) in std::env::vars_os() {
        eprintln!("{}={}", key.to_string_lossy(), value.to_string_lossy())
    }
}
```
If I run this using `RUST_LOG=asdf cargo valgrind run --manifest-path tests/corpus/Cargo.toml --bin issue-70`, the program prints all environment variables **including `RUST_LOG=asdf`**, so it appears to work as expected.

**Comment by jkcoxson** [comment]
I cannot reproduce, nor remember what I was doing to cause such an issue. If I ever work on what I was doing two years ago, I'll be sure to re-open the issue.
