### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by gilaroni** [jfrimmel/cargo-valgrind#74]
[bug report.txt](https://github.com/jfrimmel/cargo-valgrind/files/10050237/bug.report.txt)
[main.txt](https://github.com/jfrimmel/cargo-valgrind/files/10050246/main.txt)

i introduced a bug to my main.rs (main.txt), and used cargo valgrind run to detect it, but it crashed instead.
Note: I used valgrind in a docker, so it might the issue, idk.

thanks

**Comment by jfrimmel** [comment]
Hey, I'm really sorry for the huge delay. I wasn't active in this repository for a long time. Your issue should now be fixed at last (on the `master` branch, a release is yet to come in the next few days).
